name: CI for Lootopia

on:
  push:
    branches:
      - develop
      - main
      - '*'
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  web-frontend:
    if: contains(github.event.head_commit.modified, 'web-front-end/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check for outdated dependencies
        run: |
          cd web-front-end
          npm outdated || echo "Dependencies check completed."

      - name: Install dependencies
        run: |
          cd web-front-end
          npm install

      - name: Run Linter & Prettier
        run: |
          cd web-front-end
          npm run lint

      - name: Run Build
        run: |
          cd web-front-end
          npm run build
