name: Web Frontend CI

on:
  push:
    branches: ['main', 'develop', 'feature/LMD-72']
  pull_request:
    branches: ['main', 'develop']

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Check outdated dependencies
        run: |
          cd ./web-front-end
          npm outdated || echo "No outdated dependencies found."

      - name: Check dependency vulnerabilities (audit)
        id: dependency_audit
        continue-on-error: true
        run: |
          cd ./web-front-end
          npm audit --audit-level=moderate --json > dependency-audit-report.json || true

      - name: Upload audit report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-audit-report
          path: ./web-front-end/dependency-audit-report.json

      - name: Install dependencies
        run: cd ./web-front-end && npm install

      - name: Run ESLint
        run: cd ./web-front-end && npm run lint

      - name: Run Prettier
        run: cd ./web-front-end && npm run format

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: eslint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: cd ./web-front-end && npm install

      - name: Run unit tests
        run: cd ./web-front-end && npm run test

      - name: Run unit tests with coverage
        run: cd ./web-front-end && npm run test:cov
