name: Web Backend CI

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Check outdated dependencies
        run: |
          cd ./web-back-end
          npm outdated || echo "No outdated dependencies found."

      - name: Check dependency vulnerabilities
        run: |
          cd ./web-back-end
          npm audit --audit-level=moderate || echo "Dependencies checked. Some may have vulnerabilities."

      - name: Install dependencies
        run: cd ./web-back-end && npm install

      - name: Run ESLint
        run: cd ./web-back-end && npm run lint

      - name: Run prettier
        run: cd ./web-back-end && npm run format

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: eslint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: cd ./web-back-end && npm install

      - name: Run unit tests
        run: cd ./web-back-end && npm run test

      - name: Run unit tests with coverage
        run: cd ./web-back-end && npm run test:cov
