name: Web Frontend CI

on:
  push:
    branches:
      - '*' # ✅ Déclenche sur toutes les branches
  pull_request:
    branches:
      - '*' # ✅ Déclenche pour tous les PR
  workflow_dispatch: # ✅ Permet d'exécuter le workflow manuellement depuis GitHub

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: cd ./web-front-end && npm install

      - name: Run ESLint
        run: cd ./web-front-end && npm run lint
